sap:
  connect:
    # 기본 연결 설정
    host: 192.168.110.203
    sysnr: 00
    client: 300
    user: PBILLRFC
    passwd: rfcpbill
    lang: KO
    
    # 서버 설정
    serverName: SERVER
    gatewayHost: 192.168.110.203
    gatewayService: sapgw00
    programId: QH_SED
    connectionCount: 2
    threadCount: 5
    
    # Repository 설정
    repositoryDestination: ABAP_AS_WITHOUT_POOL

api:
  dev_url: http://localhost:8088
# dev_url: http://192.168.123.102:8088 # 나증
# dev_url: http://115.71.13.131:8088 # 다우